name: CD - Deploy Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------
      # 1. Checkout
      # -----------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------------------
      # 2. Configurar credenciais AWS (via Secrets)
      # -----------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # -----------------------------------------
      # 3. Criar backend do Terraform
      # -----------------------------------------
      - name: Create Terraform Backend Infra
        working-directory: deploy/terraform/backend
        run: chmod +x backend_bucket_infra.sh && ./backend_bucket_infra.sh

      # -----------------------------------------
      # 4. Descobrir dinamicamente o account-id
      # -----------------------------------------
      - name: Get AWS Account ID
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      # -----------------------------------------
      # 5. Gerar tag da imagem (dinâmica)
      # -----------------------------------------
      - name: Generate image tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # -----------------------------------------
      # 6. Login dinâmico no ECR
      # -----------------------------------------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # -----------------------------------------
      # 7. Build da imagem
      # -----------------------------------------

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn clean package -DskipTests

      # -----------------------------------------
      # 7. Build da imagem
      # -----------------------------------------
      - name: Build Docker image
        run: |
          ECR_URL="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/notification-service-prod"
          docker build -t notification-service .
          docker tag notification-service:latest "$ECR_URL:$IMAGE_TAG"

      # -----------------------------------------
      # 8. Push da imagem para o ECR
      # -----------------------------------------
      - name: Push Docker image
        run: |
          ECR_URL="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/notification-service-prod"
          docker push "$ECR_URL:$IMAGE_TAG"

      # -----------------------------------------
      # 9. Exportar tag para usar no Terraform
      # -----------------------------------------
      - name: Export variable for Terraform
        run: echo "TF_VAR_ecr_image_tag=$IMAGE_TAG" >> $GITHUB_ENV

      # -----------------------------------------
      # 10. Terraform Init/Apply
      # -----------------------------------------
      - name: Terraform Init
        working-directory: deploy/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: deploy/terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: deploy/terraform
        run: terraform apply -auto-approve
